version: '3.3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTS=-Dspring.profiles.active=prod
    container_name: broker-container
    networks:
      - app-network

networks:
  app-network:
    external: true
