version: '3.3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8082"
    environment:
      - JAVA_OPTS=-Dspring.profiles.active=prod
    container_name: broker-container
    networks:
      - totem-network


networks:
  totem-network:
    driver: bridge