version: '3.3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8082"
    environment:
      - JAVA_OPTS=-Dspring.profiles.active=prod
    container_name: comando
    networks:
      - backend-toten_totem-network

networks:
  backend-toten_totem-network:
    external: true
