version: '3.3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8082"
    environment:
      - JAVA_OPTS=-Dspring.profiles.active=prod
    container_name: broker-container
    networks:
      - backend-toten_totem-network
    deploy:
      resources:
        limits:
          memory: 1g
        reservations:
          memory: 512m

networks:
  backend-toten_totem-network:
    driver: bridge
