version: '3.3'

services:
  app-comando:
    build:
      context: .
      dockerfile: Dockerfile
    image: comando:1.0.0
    ports:
      - "8080:8082"
      - "5011:5005"
    environment:
      - TZ=America/Sao_Paulo
      - JAVA_OPTS=-Dspring.profiles.active=prod -Duser.timezone=America/Sao_Paulo
    container_name: comando
    networks:
      - backend-toten_totem-network

networks:
  backend-toten_totem-network:
    external: true
